main: com.seawars.Seawars
name: Seawars
version: 1.0
commands:
  set:
    description: Command to set area
    usage: /set
  help:
    description: Help
    usage: /help
  test:
    description: test
    usage: /test
  balance:
    description: Command to check your balance
    usage: /balance
  team:
    description: Command to join team
    usage: /team
  restartcount:
    description: Restarts Countdown
    usage: /restartcount
  coin:
    description: money
    usage: /coin
  give:
    description: Give money
    usage: /give
