main: com.seawars.Seawars
name: Seawars
version: 1.0
commands:
  set:
    description: Set Area
    usage: /set
  help:
    description: Help
    usage: /help
  test:
    description: test
    usage: /test
  test:
    description: test
    usage: /test
